print("Hi i am a calculator \n I can answer all your question... about math of course")
Num1=int(input("Now, tell me the first number: "))
Num2=int(input(f"{Num1}? what a good number, The second number is: "))
print("Okay here is the answer")
print(f"{Num1}+{Num2}={Num1+Num2}")
print(f"{Num1}-{Num2}={Num1-Num2}")
print(f"{Num1}*{Num2}={Num1*Num2}")
print(f"{Num1}/{Num2}={Num1/Num2}")
print("That's all thank you!")