Num1=int(input("Angka pertama= "))
Num2=int(input("Angka kedua= "))
print(f"Angka pertama= {Num1} \n Angka Kedua= {Num2}")
print(f"Angka pertama>Angka Kedua nilainya {Num1>Num2}")
print(f"Angka pertama<Angka Kedua nilainya {Num1<Num2}")
print(f"Angka pertama>=Angka Kedua nilainya {Num1>=Num2}")
print(f"Angka pertama<=Angka Kedua nilainya {Num1<=Num2}")
print(f"Angka pertama!=Angka Kedua nilainya {Num1!=Num2}")
print(f"Angka pertama==Angka Kedua nilainya {Num1==Num2}")